public int ii_id { get; set; }
public int ii_name { get; set; }
public int ii_name_option { get; set; }
public int ii_name_time { get; set; }
public int ii_type { get; set; }
public int ii_type_inven { get; set; }
public int ii_inven_usable { get; set; }
public int ii_type_pcbang { get; set; }
public int ii_package_result { get; set; }
public int ii_dress { get; set; }
public int ii_hide_hair { get; set; }
public int ii_hide_face { get; set; }
public int ii_hide_back { get; set; }
public int ii_class_a { get; set; }
public int ii_class_b { get; set; }
public int ii_class_c { get; set; }
public int ii_class_d { get; set; }
public int ii_class_e { get; set; }
public int ii_class_f { get; set; }
public int ii_class_g { get; set; }
public int ii_class_h { get; set; }
public int ii_class_i { get; set; }
public int ii_class_j { get; set; }
public int ii_class_k { get; set; }
public int ii_class_l { get; set; }
public int ii_class_m { get; set; }
public int ii_class_n { get; set; }
public int ii_class_o { get; set; }
public int ii_class_p { get; set; }
public int ii_grade { get; set; }
public int ii_stocks { get; set; }
public int ii_usable { get; set; }
public int ii_upgradable { get; set; }
public int ii_consumable { get; set; }
public int ii_weaponinfo { get; set; }
public int ii_fullseteffectinfo { get; set; }
public int ii_durable_value { get; set; }
public int ii_durable_factor { get; set; }
public int ii_durable_repair_type { get; set; }
public int ii_limited_mod { get; set; }
public int ii_limited_time { get; set; }
public int ii_buy_coupon { get; set; }
public int ii_buy_cash { get; set; }
public int ii_buy_point { get; set; }
public int ii_sell_point { get; set; }
public int ii_bonus_point { get; set; }
public int ii_bonus_pack { get; set; }
public int ii_dioramainfo { get; set; }
public int ii_dummyinfo { get; set; }
public int ii_icon { get; set; }
public int ii_iconsmall { get; set; }
public int ii_meshfilename { get; set; }
public int ii_nodename { get; set; }
public int ii_color_ambient { get; set; }
public int ii_color_diffuse { get; set; }
public int ii_color_specular { get; set; }
public int ii_color_emittance { get; set; }
public int ii_sfx { get; set; }
public int ef_effect_1 { get; set; }
public int ef_target_1 { get; set; }
public int ef_effect_2 { get; set; }
public int ef_target_2 { get; set; }
public int ef_effect_3 { get; set; }
public int ef_target_3 { get; set; }
public int ii_desc { get; set; }
public int ii_immediately_set { get; set; }
public int ii_is_trade { get; set; }
public int ii_ei_exp { get; set; }
public int ii_evolution_type { get; set; }
